### PR TITLE
API and storage rewrite with stateless mode

### PR DESCRIPTION
**Pull request by Derkades**

### CODE REVIEW

**Comment by Derkades** [comment]
image

**Comment by Aberdeener** [comment]
Looks good, has this been tested?

**Comment by Derkades** [comment]
Not done yet, mainly because I need https://github.com/NamelessMC/Nameless/issues/1876 first. When I am done I'll mark this PR as ready

**Comment by Aberdeener** [comment]
NamelessMC/Nameless#1876 is complete

**Comment by Derkades** [comment]
Is there a file I haven't touched yet?

**Comment by Derkades** [comment]
@Aberdeener :shipit:

**Comment by Aberdeener** [comment]
its been a wild ride. thank you for everything ☮️

**Pull request merged**
